<a href="https://colab.research.google.com/github/zainulabidin73622/DEEP_LEARNING/blob/main/celoss_multiclass_classification_180325.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Ground truth labels (one-hot encoded)
y_true = np.array([
    [1, 0, 0,1,0],  # Sample 1: Class 1
    [0, 1, 0,1,1],  # Sample 2: Class 2
    [0, 0, 1,1,0],  # Sample 3: Class 3


])

# Model predictions (logits)
logits = np.array([
    [2.0, 1.0, 0.1,0.2,0.3],  # Sample 1
    [0.5, 2.5, 0.2,0.3,0.1],  # Sample 2
    [0.1, 0.2, 3.0,0.6,1.5] ,  # Sample 3


])

# Softmax function
def softmax(x):
    exp_x = np.exp(x - np.max(x, axis=-1, keepdims=True))  # Numerical stability
    return exp_x / np.sum(exp_x, axis=-1, keepdims=True)

# Compute softmax probabilities
probs = softmax(logits)
print("Softmax Probabilities:\n", probs)

# Compute log(probs)
log_probs = np.log(probs)
print("\nLog of Softmax Probabilities:\n", log_probs)

# Compute y_true * log(probs)
y_true_log_probs = y_true * log_probs
print("\ny_true * log(probs):\n", y_true_log_probs)

# Compute CE loss for each sample
ce_loss = -np.sum(y_true_log_probs, axis=-1)
print("\nCE Loss per Sample:", ce_loss)

# Average CE loss for the dataset
avg_ce_loss = np.mean(ce_loss)
print("\nAverage CE Loss for the Dataset:", avg_ce_loss)

Softmax Probabilities:
 [[0.5360693  0.19720887 0.08017914 0.08861166 0.09793103]
 [0.09417149 0.69583842 0.06976396 0.07710109 0.06312504]
 [0.03848635 0.042534   0.69945654 0.06345327 0.15606985]]

Log of Softmax Probabilities:
 [[-0.62349184 -1.62349184 -2.52349184 -2.42349184 -2.32349184]
 [-2.3626378  -0.3626378  -2.6626378  -2.5626378  -2.7626378 ]
 [-3.25745162 -3.15745162 -0.35745162 -2.75745162 -1.85745162]]

y_true * log(probs):
 [[-0.62349184 -0.         -0.         -2.42349184 -0.        ]
 [-0.         -0.3626378  -0.         -2.5626378  -2.7626378 ]
 [-0.         -0.         -0.35745162 -2.75745162 -0.        ]]

CE Loss per Sample: [3.04698369 5.68791339 3.11490324]

Average CE Loss for the Dataset: 3.949933439390572
